## makeCacheMatrix is a function that generates a matrix 
## and caches its inverse using the solve function in R.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve is a function that will solve for the inverse of the matrix
## that is generated by makeCacheMatrix. cacheSolve will pull the inverse
## from the cache if the inverse has already been solved and display
## "getting cached data" otherwise, it will solve for the inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getinv()
  if(!is.null(m)) {
      message("getting cached data")
      return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
